// <auto-generated />
using System;
using Currencies.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Currencies.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190830063711_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Currencies.Models.CurrencyInfo", b =>
                {
                    b.Property<string>("CharCode")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Nominal");

                    b.Property<int>("NumCode");

                    b.HasKey("CharCode");

                    b.ToTable("CurrencyInfos");
                });

            modelBuilder.Entity("Currencies.Models.CurrencyValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CurrencyInfoId");

                    b.Property<DateTime>("Date");

                    b.Property<float>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyInfoId");

                    b.ToTable("CurrencyValues");
                });

            modelBuilder.Entity("Currencies.Models.CurrencyValue", b =>
                {
                    b.HasOne("Currencies.Models.CurrencyInfo", "CurrencyInfo")
                        .WithMany()
                        .HasForeignKey("CurrencyInfoId");
                });
#pragma warning restore 612, 618
        }
    }
}
